export default `
query JobByID($id: ID) {
    jobs(filters: {id:{eq:$id}}) {
        data{
            id
            attributes{
                slug
                title
                description
                url
                type
                locations{
                  data{
                    attributes{
                      name
                      slug
                    }
                  }
                }
                salarymin
                salarymax
                date
                skills{
                  data{
                    attributes{
                      name
                      slug
                    }
                  }
                }
              company{
                data{
                  attributes{
                    name
                    logo{
                      data{
                        attributes{
                          url
                        }
                      }
                    }
                  }
                }
              }
            }
          }
  }
}
  `;
