export default `
    query PostBySlug($status: String, $slug: String) {
      posts(filters: {status:{eq:$status}, slug:{eq:$slug}, type:{eq:"tool"}}) {
        data {
          id
          attributes {
            title
            slug
            content
            link
            excerpt
            #tagline
            date
            updatedAt
            likeCount{
              total
              like
              fire
              unicorn
            }
            likes{
              data{
                id
                attributes{
                  like
                  love
                  fire
                  unicorn
                  total
                  user{
                    data{
                      id
                    }
                  }
                }
              }
            }
            seo{
                metaDesc
                canonical
                opengraphModifiedTime
                opengraphPublishedTime
                opengraphTitle
                opengraphDescription
                opengraphImage
            }
            ogImage: seo {
              opengraphImage
            }
            tags{
              data{
                attributes{
                  name
                  slug
                }
              }
            }
            localizations {
              data{
                attributes {
                  locale
                  title
                  excerpt
                }
              }
            }
            legacyMedia {
              gallery {
                medium
                thumb
              }
            }
            gallery{
              data{
                attributes{
                  blurhash
                  url
                  caption
                  alternativeText
                }
              }
            }
            legacyFeaturedImage:legacyMedia{
                mediaItemUrl:featuredImage
                imgUrl
                logoNew
            }
            featuredImage{
              data{
                attributes{
                  blurhash
                  url
                  formats
                }
              }
            }
            logo{
              data{
                attributes{
                  url
                  blurhash
                }
              }
            }
            author: user {
              data {
                id
                attributes {
                  name: username
                  displayName:username
                  firstName
                  lastName:secondName
                  legacyAvatar
                  avatar{
                    data{
                      attributes{
                        url
                      }
                    }
                  }
                  slug
                }
              }
            }
            interviews{
              data{
                id
              }
            }
            creators {
              data {
                id
                attributes {
                  name: username
                  displayName:username
                  firstName
                  lastName:secondName
                  legacyAvatar
                  jobrole
                  avatar{
                    data{
                      attributes{
                        url
                      }
                    }
                  }
                  slug
                }
              }
            }
            relatedTools{
              localizations{
                data{
                  attributes{
                    title
                    locale
                  }
                }
              }
              title
              slug
              tags{
                data{
                    attributes{
                    name
                    slug
                    }
                }
              }
              legacyFeaturedImage:legacyMedia{
                mediaItemUrl:featuredImage
                imgUrl
                logoNew
            }
            logo{
              data{
                attributes{
                  blurhash
                  url
                }
              }
            }
            featuredImage{
              data{
                attributes{
                  blurhash
                  url
                }
              }
            }
              user{
                data{
                  attributes{
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
